name: Gitconvex Server Pipeline

on:
  push:
    branches: [ main ]

jobs:
  libgit2-setup-test:
    name: Setup Libgit2 with Homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Install libssh2 and libgit2
        run: |
          brew install libssh2
          brew install libgit2

  gitconvex-test:
    name: Gitconvex server test
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_PATH: /home/linuxbrew/.linuxbrew/Cellar/libgit2/1.1.0/lib/pkgconfig/

    steps:
      - name: Install libgit2 from Homebrew
        run: |
          brew install libssh2
          brew install libgit2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run Go Test
        run: |
          sudo cp /home/linuxbrew/.linuxbrew/Cellar/libgit2/1.1.0/lib/lib* /usr/lib
          export PATH="/home/linuxbrew/.linuxbrew/Cellar/libgit2/1.1.0/lib/:$PATH"
          git config --global user.name "${{ secrets.ACTION_USER_NAME }}" && git config --global user.email "${{ secrets.ACTION_USER_EMAIL }}"
          export GOTESTENV=ci && go test -v ./...

  gitconvex-build:
    needs:
      - gitconvex-test
      - libgit2-setup-test

    name: Gitconvex Build
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_PATH: /home/linuxbrew/.linuxbrew/Cellar/libgit2/1.1.0/lib/pkgconfig/

    steps:
      - name: Install libgit2 from Homebrew
        run: |
          brew install libssh2
          brew install libgit2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Go bundle
        run: go build -v .

  gitconvex-integration:
    needs:
      - libgit2-setup-test
      - gitconvex-test
      - gitconvex-build

    name: Gitconvex Unified Repo Integration
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_PATH: /home/linuxbrew/.linuxbrew/Cellar/libgit2/1.1.0/lib/pkgconfig/

    steps:
      - name: Install libgit2 from Homebrew
        run: |
          brew install libssh2
          brew install libgit2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Integration checkup
        run: |
          export TARGET_BRANCH=${{ secrets.TARGET_BRANCH }}
          git clone https://github.com/neel1996/gitconvex-server.git $HOME/gitconvex-server
          cd $HOME/gitconvex-server
          git checkout ${{ github.head_ref }}
          export LATEST_COMMIT=$(git log --oneline -1 --pretty=format:%s)
          git clone https://github.com/neel1996/gitconvex.git $HOME/gitconvex
          git config --global user.name "${{ secrets.ACTION_USER_NAME }}" && git config --global user.email "${{ secrets.ACTION_USER_EMAIL }}"
          cd $HOME/gitconvex
          git checkout $TARGET_BRANCH
          cd $GITHUB_WORKSPACE
          rm README.md
          rm -rf .git/ .github/ .gitignore gitconvex-server tests/
          cp -rp * $HOME/gitconvex/
          cd $HOME/gitconvex/
          rm -rf libgit2-1.1.0*
          echo "Commit Message --> $LATEST_COMMIT"
          git status
          git add --all
          git commit -m "$LATEST_COMMIT"
          git log -1
          git remote set-url origin https://${{ secrets.ACTION_USER_NAME }}:${{ secrets.AUTH_TOKEN }}@github.com/neel1996/gitconvex
          git push -u origin $TARGET_BRANCH
