name: Gitconvex Server Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Gitconvex Server Main Pipeline
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Running Test Cases
        run: export GOTESTENV=ci && go test -v ./...

      - name: Build
        run: go build -v .

      - name: Droplet commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            /opt/workroom/gitconvex-deploy.sh gitconvex-server
